{
 "title": "Data",
 "time": { "from": "2017-01-01T02:00:00.000Z", "to": "2017-01-31T23:03:39.000Z" },
 "panels": [
  {
   "title": "RMSE",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeEpoch(Date),Value, Algoritm_Names.Name as metric FROM Algoritm_Names INNER JOIN Rmse_Values ON Algoritm_Names.Id = Rmse_Values.AlgId WHERE Rmse_Values.Device_Id = 1 AND Rmse_Values.AlgId = 1"
    },
    {
     "rawSql": "SELECT $__timeEpoch(Date),Value, Algoritm_Names.Name as metric FROM Algoritm_Names INNER JOIN Rmse_Values ON Algoritm_Names.Id = Rmse_Values.AlgId WHERE Rmse_Values.Device_Id = 1 AND Rmse_Values.AlgId = 2"
    },
    {
     "rawSql": "SELECT $__timeEpoch(Date),Value, Algoritm_Names.Name as metric FROM Algoritm_Names INNER JOIN Rmse_Values ON Algoritm_Names.Id = Rmse_Values.AlgId WHERE Rmse_Values.Device_Id = 1 AND Rmse_Values.AlgId = 3"
    },
    {
     "rawSql": "SELECT $__timeEpoch(Date),Value, Algoritm_Names.Name as metric FROM Algoritm_Names INNER JOIN Rmse_Values ON Algoritm_Names.Id = Rmse_Values.AlgId WHERE Rmse_Values.Device_Id = 1 AND Rmse_Values.AlgId = 4"
    },
    {
     "rawSql": "SELECT $__timeEpoch(Date),Value, Algoritm_Names.Name as metric FROM Algoritm_Names INNER JOIN Rmse_Values ON Algoritm_Names.Id = Rmse_Values.AlgId WHERE Rmse_Values.Device_Id = 1 AND Rmse_Values.AlgId = 5"
    }
   ]
  },
  {
   "title": "AVG RMSE Alg1",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(Value) FROM Rmse_Values WHERE Rmse_Values.Device_Id = 1 AND Rmse_Values.AlgId = 1"
    }
   ]
  },
  {
   "title": "AVG RMSE Alg2",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(Value) FROM Rmse_Values WHERE Rmse_Values.Device_Id = 1 AND Rmse_Values.AlgId = 2"
    }
   ]
  },
  {
   "title": "AVG RMSE Alg3",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(Value) FROM Rmse_Values WHERE Rmse_Values.Device_Id = 1 AND Rmse_Values.AlgId = 3"
    }
   ]
  },
  {
   "title": "Values",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 20, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeEpoch(DateTime),Value, Algoritm_Names.Name as metric FROM Algoritm_Names INNER JOIN Algoritm_Results ON Algoritm_Names.Id = Algoritm_Results.Algoritm_Id WHERE Algoritm_Results.Device_Id = 1 AND Algoritm_Results.Algoritm_Id = 1\n"
    },
    {
     "rawSql": "SELECT $__timeEpoch(DateTime),Value, Algoritm_Names.Name as metric FROM Algoritm_Names INNER JOIN Algoritm_Results ON Algoritm_Names.Id = Algoritm_Results.Algoritm_Id WHERE Algoritm_Results.Device_Id = 1 AND Algoritm_Results.Algoritm_Id = 2"
    },
    {
     "rawSql": "SELECT $__timeEpoch(DateTime),Value, Algoritm_Names.Name as metric FROM Algoritm_Names INNER JOIN Algoritm_Results ON Algoritm_Names.Id = Algoritm_Results.Algoritm_Id WHERE Algoritm_Results.Device_Id = 1 AND Algoritm_Results.Algoritm_Id = 3"
    },
    {
     "rawSql": "SELECT $__timeEpoch(DateTime),Value, Algoritm_Names.Name as metric FROM Algoritm_Names INNER JOIN Algoritm_Results ON Algoritm_Names.Id = Algoritm_Results.Algoritm_Id WHERE Algoritm_Results.Device_Id = 1 AND Algoritm_Results.Algoritm_Id = 4"
    },
    {
     "rawSql": "SELECT $__timeEpoch(DateTime),Value, Algoritm_Names.Name as metric FROM Algoritm_Names INNER JOIN Algoritm_Results ON Algoritm_Names.Id = Algoritm_Results.Algoritm_Id WHERE Algoritm_Results.Device_Id = 1 AND Algoritm_Results.Algoritm_Id = 5"
    }
   ]
  },
  {
   "title": "AVG RMSE Alg4",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(Value) FROM Rmse_Values WHERE Rmse_Values.Device_Id = 1 AND Rmse_Values.AlgId = 4"
    }
   ]
  },
  {
   "title": "AVG RMSE Alg5",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(Value) FROM Rmse_Values WHERE Rmse_Values.Device_Id = 1 AND Rmse_Values.AlgId = 5"
    }
   ]
  }
 ]
}